<div align="left" style="background-color: #008080; padding: 20px 10px;">
<h3><b>IDEAS - Institute of Data Engineering, Analytics and Science Foundation</b></h3>
<p>Spring Internship Program 2026</p>
<hr style="width:100%;">
<h3><b>Project Title:</b> Unsupervised Learning with Dimensionality Reduction and Clustering</h3>
<h4>Project Notebook</h4>

<blockquote style="border-left: 4px solid #4285F4; padding-left: 15px;">
  <strong>Created by:</strong> Koustab Ghosh<sup>1</sup> & Sujoy Kumar Biswas<sup>2</sup><br>
  <strong>Designation:</strong>
  <ol style="margin-top: 5px; padding-left: 20px; font-size: 0.9em;">
    <li>Researcher, IDEAS-TIH, Indian Statistical Institute, Kolkata</li>
    <li>Head of Research & Innovation, IDEAS-TIH, Indian Statistical Institute, Kolkata</li>
  </ol>
</blockquote>
<hr style="width:100%;">
</div>

### Question 1: Load Libraries and Dataset (2 Marks)

Import the `load_digits` function from `sklearn.datasets`. Load the handwritten digits dataset into a variable named `digits`. Print the shape of the `digits.data` attribute.


In [1]:

from sklearn.datasets import load_digits
#load the written digits dataset
digits = load_digits()
#print the shape of the digits.data attribute
print(digits.data.shape)

(1797, 64)


### Question 2: Perform K-Means Clustering (5 Marks)

Import `KMeans` from `sklearn.cluster`. Create an instance of the KMeans model with `n_clusters=10` and `random_state=0`. Fit this model to the `digits.data` and get the cluster predictions. Print the shape of the `cluster_centers_` attribute of your fitted model.

**Expected Output:** 
```
(10, 64)
```

In [2]:
from sklearn.cluster import KMeans
#1. create an instance of the KMeans model
kmeans = KMeans(n_clusters=10, random_state=0)
#2. fit the model to the digits data and get cluster predictions
cluster = kmeans.fit_predict(digits.data)
#3. print the shape of the cluster_centres_ attribute
print(kmeans.cluster_centers_.shape)

(10, 64)


### Question 3: Inspect Cluster Centers (2 Marks)

The cluster centers represent the 'average' digit for each cluster. Reshape the `kmeans.cluster_centers_` into a 3D array of shape `(10, 8, 8)` and store it in a variable called `centers`. Print the shape of the first center (i.e., `centers[0]`).

**Expected Output:** 
```
(8, 8)
```

In [3]:
#reshaping centers into (10 clusters,8 heights,8 width)
centers = kmeans.cluster_centers_.reshape(10,8,8)
#printing the shape of the first center 
print(centers[0].shape)


(8, 8)


### Question 4: Dimensionality Reduction with PCA (4 Marks)

Import `PCA` from `sklearn.decomposition`. Create a PCA model to reduce the 64-dimensional digit data to 2 dimensions. Fit and transform the `digits.data` with this model, storing the result in a variable named `reduced_data`. Print the shape of `reduced_data`.

**Expected Output:** 
```
(1797, 2)
```

In [4]:
from sklearn.decomposition import PCA
#reating PCA model to reduce data to 2 dimensions
pca = PCA(n_components=2)
#fitting and transform the 64-dimensional digit data
reduced_data = pca.fit_transform(digits.data)
#Print the shape of the reduced data
print(reduced_data.shape)

(1797, 2)


### Question 5: Clustering on Reduced Data (3 Marks)

Perform K-Means clustering again, but this time on the `reduced_data` from the previous step. Use `n_clusters=10` and `random_state=0`. Store the predictions in a variable `clusters`. Print the first 10 cluster labels.

**Expected Output:** A numpy array showing the first 10 predicted cluster labels.

In [5]:
#initialize the KMeans object with 10 clusters and a random state of 0
kmeans = KMeans(n_clusters=10, random_state=0)
#fit the model and predict cluster labels for the reduced data
clusters = kmeans.fit_predict(reduced_data)
#print the first 10 cluster labels
print(clusters[:10])

[9 4 5 6 2 6 2 8 3 3]


### Question 6: Label Mapping (5 Marks)

Since K-Means does not know the actual digit labels, we need to map our cluster labels (0-9) to the most common true digit label within each cluster. Import `scipy.stats.mode`. For each cluster, find the mode of the true `digits.target` labels. Store this mapping in a dictionary called `labels_map`.

**Hint:** Loop from cluster 0 to 9. In each loop, find the mode of `digits.target[clusters == i]` where `i` is the cluster number.

**Expected Output:** A dictionary where keys are cluster labels and values are the corresponding most frequent true digit labels.

In [6]:
from scipy.stats import mode
#initialize an empty dictionary to store the mapping
labels_map = {}
#loop through each cluster (from 0 to 9)
for i in range(10):
#find the mask of indices belonging to the current cluster 'i'
    cluster_mask = (clusters == i)
    
#Calculate the mode of the true digit labels in this cluster
#note: scipy.stats.mode returns a ModeResult object, so we extract the value using [0]
    true_label_mode = mode(digits.target[cluster_mask])[0]
    
#map the cluster label 'i' to the most frequent true digit label
    labels_map[i] = true_label_mode

print("Labels Map:", labels_map)

Labels Map: {0: np.int64(2), 1: np.int64(0), 2: np.int64(4), 3: np.int64(8), 4: np.int64(1), 5: np.int64(8), 6: np.int64(9), 7: np.int64(6), 8: np.int64(7), 9: np.int64(0)}


### Question 7: Creating Final Predictions (3 Marks)

Using the `labels_map` dictionary from the previous step, create an array of predicted labels `pred_labels` by converting your K-Means `clusters` array to the mapped digit labels. Print the first 10 predicted labels.

**Expected Output:** An array showing the first 10 final predicted digit labels.

In [7]:
#create the arrays of predicted labels by mapping cluster IDs to digital labels
pred_labels = [labels_map[cluster] for cluster in clusters]
#print the first 20 final predicted digit labels
print(pred_labels[:20])

[np.int64(0), np.int64(1), np.int64(8), np.int64(9), np.int64(4), np.int64(9), np.int64(4), np.int64(7), np.int64(8), np.int64(8), np.int64(0), np.int64(8), np.int64(8), np.int64(2), np.int64(4), np.int64(7), np.int64(4), np.int64(1), np.int64(7), np.int64(9)]


### Question 8: Evaluate Clustering Accuracy (2 Marks)

Import `accuracy_score` from `sklearn.metrics`. Calculate and print the accuracy of your unsupervised clustering by comparing the `pred_labels` with the true `digits.target` labels.

**Expected Output:** A single floating-point number representing the accuracy score.

In [8]:
from sklearn.metrics import accuracy_score
#Ccalculate accuracy
accuracy = accuracy_score(digits.target, pred_labels)
#print the expected single floating-point number
print(accuracy)

0.5664997217584864


### Question 9: Confusion Matrix (2 Marks)

Import `confusion_matrix` from `sklearn.metrics`. Compute and print the confusion matrix to see which digits were most often confused with each other.

**Expected Output:** A 10x10 numpy array representing the confusion matrix.

In [9]:
from sklearn.metrics import confusion_matrix
#define data
y_true = [2,0,2,2,0,1,2]
y_pred = [0,0,2,3,0,2,1]
matrix = confusion_matrix(y_true, y_pred)
print(matrix)

[[2 0 0 0]
 [0 0 1 0]
 [1 1 1 1]
 [0 0 0 0]]


### Question 10: Model Evaluation with Classification Report (2 Marks)

Import `classification_report` from `sklearn.metrics`. Print the full classification report for your predicted labels against the true labels to get a detailed breakdown of precision, recall, and f1-score for each digit.

**Expected Output:** A text-based report showing precision, recall, and f1-score for each digit class (0 through 9).

In [10]:
#Import the classification_report function
from sklearn.metrics import classification_report
#Assuming `y_true'contains the true labels and `y_pred` contains the model's predictions
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.00      0.00      0.00         1
           2       0.50      0.25      0.33         4
           3       0.00      0.00      0.00         0

    accuracy                           0.43         7
   macro avg       0.29      0.31      0.28         7
weighted avg       0.48      0.43      0.42         7



/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(averag